### ISSUE TITLE
does not work with FW v5.22.9 - 5.24.4

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-toc#9]
Clicking the TOC button in the nav bar displays the modal shadow but does not load Drawer content. The same behaviour applies to clicking the PLP nav button and the Drawer hamburger.

My testing of various combinations of FW, TOC, and PLP point to behaviour breaking in FW 5.22.9. I found the expected behaviour in FW 5.22.8. Versions of PLP and TOC do not change between these two FW versions, suggesting that the difference may lie in adapt-contrib-core--perhaps with changes in v6.21.0  

Course configuration used during testing included:

 "_start": {
    "_isEnabled": true,
    "_startIds": [
      {
        "_id": "co-05",
        "_skipIfComplete": false,
        "_className": ""
      }
    ],
    "_force": true,
    "_isMenuDisabled": true
  },

 "_pageLevelProgress": {
    "_isEnabled": true,
    "_showPageCompletion": false,
    "_isCompletionIndicatorEnabled": false,
    "_isShownInNavigationBar": true
  },

"_toc": {
    "_excludeContentObjects": []
  }

**Comment by swashbuck** [comment]
The latest version of `adapt-toc` has a dependency on the Tooltip API which was introduced in FW [5.30.2](https://github.com/adaptlearning/adapt_framework/releases/tag/v5.30.2) and [6.33.0](https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.33.0) of Core. So, we should probably bump the FW requirements to at least 5.30.2 in _package.json_.
